FROM alpine:3.20
RUN apk add --no-cache mariadb-client tar gzip python3 py3-pip curl \
    && pip install --break-system-packages --no-cache-dir oci-cli
COPY backup.sh /backup.sh
COPY restore.sh /restore.sh
RUN chmod +x /backup.sh /restore.sh
ENTRYPOINT ["/backup.sh"]
